// Bower name generation utility

// Japanese adjectives for bower names
const japaneseAdjectives = [
  '美しい', '静かな', '温かい', '優雅な', '穏やかな', '輝く', '清らかな', '豊かな',
  '新鮮な', '活気ある', '心地よい', '魅力的な', '素晴らしい', '愛らしい', '上品な',
  '華やかな', '神秘的な', '平和な', '希望に満ちた', '創造的な'
]

// English adjectives for bower names
const englishAdjectives = [
  'Beautiful', 'Serene', 'Warm', 'Elegant', 'Peaceful', 'Bright', 'Pure', 'Rich',
  'Fresh', 'Vibrant', 'Cozy', 'Charming', 'Wonderful', 'Lovely', 'Refined',
  'Radiant', 'Mystical', 'Tranquil', 'Hopeful', 'Creative'
]

// Japanese suffixes for bower names
const japaneseSuffixes = [
  'の巣', 'の庭', 'の森', 'の泉', 'の空間', 'の世界', 'の場所', 'の隠れ家',
  'の聖域', 'の楽園', 'の宝庫', 'の図書館', 'の研究室', 'の工房'
]

// English suffixes for bower names
const englishSuffixes = [
  ' Nest', ' Garden', ' Forest', ' Spring', ' Space', ' World', ' Place', ' Haven',
  ' Sanctuary', ' Paradise', ' Treasury', ' Library', ' Lab', ' Workshop'
]

/**
 * Generate a bower name from keywords
 */
export function generateBowerName(keywords: string[], language: 'ja' | 'en' = 'ja'): string {
  if (keywords.length === 0) {
    return language === 'ja' ? '新しいバウアー' : 'New Bower'
  }

  // If only one keyword, use it directly with suffix
  if (keywords.length === 1) {
    const keyword = keywords[0]
    const suffixes = language === 'ja' ? japaneseSuffixes : englishSuffixes
    const randomSuffix = suffixes[Math.floor(Math.random() * suffixes.length)]
    return keyword + randomSuffix
  }

  // If multiple keywords, combine them creatively
  const adjectives = language === 'ja' ? japaneseAdjectives : englishAdjectives
  const suffixes = language === 'ja' ? japaneseSuffixes : englishSuffixes
  
  // Pick a random adjective and the first keyword
  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)]
  const mainKeyword = keywords[0]
  const randomSuffix = suffixes[Math.floor(Math.random() * suffixes.length)]
  
  if (language === 'ja') {
    return `${randomAdjective}${mainKeyword}${randomSuffix}`
  } else {
    return `${randomAdjective} ${mainKeyword}${randomSuffix}`
  }
}

/**
 * Generate multiple bower name suggestions
 */
export function generateBowerNameSuggestions(keywords: string[], language: 'ja' | 'en' = 'ja', count: number = 3): string[] {
  const suggestions: string[] = []
  
  for (let i = 0; i < count; i++) {
    suggestions.push(generateBowerName(keywords, language))
  }
  
  // Remove duplicates
  return [...new Set(suggestions)]
}

/**
 * Check if a bower name is auto-generated (contains common suffixes)
 */
export function isAutoGeneratedName(name: string, language: 'ja' | 'en' = 'ja'): boolean {
  if (!name) return true
  
  const suffixes = language === 'ja' ? japaneseSuffixes : englishSuffixes
  const adjectives = language === 'ja' ? japaneseAdjectives : englishAdjectives
  
  // Check if name contains any of the suffixes
  const hasSuffix = suffixes.some(suffix => name.includes(suffix))
  
  // Check if name contains any of the adjectives
  const hasAdjective = adjectives.some(adj => name.includes(adj))
  
  // Check for default names
  const defaultNames = [
    '新しいバウアー', 'New Bower', 'Untitled Bower', '無題のバウアー'
  ]
  
  return hasSuffix || hasAdjective || defaultNames.includes(name)
}