services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    networks:
      - feed-bower-network
    depends_on:
      - dynamodb-local
      - dynamodb-admin

  # DynamoDB Local for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - feed-bower-network

  # DynamoDB Admin interface
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - feed-bower-network
    restart: unless-stopped

  # Magnito - AWS Cognito Emulator for Amplify UI
  magnito:
    image: frourio/magnito:latest
    container_name: magnito
    ports:
      - "9229:9229"
    volumes:
      - ../.cognito:/app/.cognito:cached
    environment:
      - PORT=9229
      - HOST=0.0.0.0
      # Cognito Configuration
      - COGNITO_USER_POOL_ID=ap-northeast-1_xSR9dPrp8
      - COGNITO_USER_POOL_CLIENT_ID=73ev8tq1pmg6bum65mnj6vu3nm
      - COGNITO_REGION=ap-northeast-1
      # Optional: Custom user pool configuration
      - COGNITO_USER_POOL_NAME=feed-bower-pool
      - COGNITO_USER_POOL_CLIENT_NAME=feed-bower-client
      # CORS Configuration
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - feed-bower-network
    restart: unless-stopped

networks:
  feed-bower-network:
    driver: bridge

volumes:
  dynamodb-data:
